# Generated by Django 4.1.7 on 2023-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRISLEYASSIGNMENT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genre',
            new_name='ticketnumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verificationcode',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.IntegerField(blank=True, default=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ticketprice',
            field=models.IntegerField(blank=True, default=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.IntegerField(blank=True),
        ),
    ]
